"""empty message

Revision ID: 0a93f01eeb27
Revises: 5e2ce62632a6
Create Date: 2020-08-27 09:42:17.578217

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0a93f01eeb27'
down_revision = '5e2ce62632a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_entity_link_entity_in_id'), 'entity_link', ['entity_in_id'], unique=False)
    op.create_index(op.f('ix_entity_link_entity_out_id'), 'entity_link', ['entity_out_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_link_entity_out_id'), table_name='entity_link')
    op.drop_index(op.f('ix_entity_link_entity_in_id'), table_name='entity_link')
    # ### end Alembic commands ###
