"""empty message

Revision ID: 346adc288729
Revises: 72dd6c38dbf0
Create Date: 2020-07-03 13:54:10.492568

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = '346adc288729'
down_revision = '72dd6c38dbf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependent_link',
    sa.Column('output_file_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('dependent_file_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.ForeignKeyConstraint(['dependent_file_id'], ['dependent_file.id'], ),
    sa.ForeignKeyConstraint(['output_file_id'], ['output_file.id'], ),
    sa.PrimaryKeyConstraint('output_file_id', 'dependent_file_id')
    )
    op.drop_table('dependent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependent',
    sa.Column('a', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('b', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['a'], ['output_file.id'], name='dependent_a_fkey'),
    sa.ForeignKeyConstraint(['b'], ['dependent_file.id'], name='dependent_b_fkey')
    )
    op.drop_table('dependent_link')
    # ### end Alembic commands ###
