"""empty message

Revision ID: a372d087e3a0
Revises: 346adc288729
Create Date: 2020-07-03 14:02:40.153565

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = 'a372d087e3a0'
down_revision = '346adc288729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children_file', sa.Column('parent_file_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True))
    op.create_foreign_key(None, 'children_file', 'output_file', ['parent_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'children_file', type_='foreignkey')
    op.drop_column('children_file', 'parent_file_id')
    # ### end Alembic commands ###
