"""empty message

Revision ID: b0c7977be2c0
Revises: c68c2a62cfac
Create Date: 2020-06-30 18:10:36.835728

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b0c7977be2c0'
down_revision = 'c68c2a62cfac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('output_file', sa.Column('frame_start', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('output_file', 'frame_start')
    # ### end Alembic commands ###
