"""empty message

Revision ID: b2d6e9da4b91
Revises: a372d087e3a0
Create Date: 2020-07-03 16:17:39.503528

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = 'b2d6e9da4b91'
down_revision = 'a372d087e3a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('children_file_uc', 'children_file', ['parent_file_id', 'output_type_id'])
    op.drop_index('ix_children_file_asset_instance_id', table_name='children_file')
    op.drop_constraint('children_file_asset_instance_id_fkey', 'children_file', type_='foreignkey')
    op.drop_constraint('children_file_entity_id_fkey', 'children_file', type_='foreignkey')
    op.drop_column('children_file', 'asset_instance_id')
    op.drop_column('children_file', 'entity_id')
    op.add_column('dependent_file', sa.Column('project_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True))
    op.create_unique_constraint(None, 'dependent_file', ['path'])
    op.create_foreign_key(None, 'dependent_file', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dependent_file', type_='foreignkey')
    op.drop_constraint(None, 'dependent_file', type_='unique')
    op.drop_column('dependent_file', 'project_id')
    op.add_column('children_file', sa.Column('entity_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('children_file', sa.Column('asset_instance_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('children_file_entity_id_fkey', 'children_file', 'entity', ['entity_id'], ['id'])
    op.create_foreign_key('children_file_asset_instance_id_fkey', 'children_file', 'asset_instance', ['asset_instance_id'], ['id'])
    op.create_index('ix_children_file_asset_instance_id', 'children_file', ['asset_instance_id'], unique=False)
    op.drop_constraint('children_file_uc', 'children_file', type_='unique')
    # ### end Alembic commands ###
