"""empty message

Revision ID: ca67fc88b62a
Revises: b0c7977be2c0
Create Date: 2020-07-03 10:19:13.951268

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'ca67fc88b62a'
down_revision = 'b0c7977be2c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('output_file', sa.Column('frame_end', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('output_file', 'frame_end')
    # ### end Alembic commands ###
