"""empty message

Revision ID: e225f551ff45
Revises: ca67fc88b62a
Create Date: 2020-07-03 10:28:45.587193

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = 'e225f551ff45'
down_revision = 'ca67fc88b62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('children_file',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('output_type_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('file_status_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('entity_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('asset_instance_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('temporal_entity_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.ForeignKeyConstraint(['asset_instance_id'], ['asset_instance.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['file_status_id'], ['file_status.id'], ),
    sa.ForeignKeyConstraint(['output_type_id'], ['output_type.id'], ),
    sa.ForeignKeyConstraint(['temporal_entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_file_asset_instance_id'), 'children_file', ['asset_instance_id'], unique=False)
    op.create_index(op.f('ix_children_file_output_type_id'), 'children_file', ['output_type_id'], unique=False)
    op.create_table('dependent_file',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source_output_file_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=32), nullable=True),
    sa.Column('extension', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=400), nullable=True),
    sa.Column('temporal_entity_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.ForeignKeyConstraint(['source_output_file_id'], ['output_file.id'], ),
    sa.ForeignKeyConstraint(['temporal_entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )    
    op.create_table('dependent',
    sa.Column('output_file', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('dependent_file', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.ForeignKeyConstraint(['dependent_file'], ['dependent_file.id'], ),
    sa.ForeignKeyConstraint(['output_file'], ['output_file.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependent_file')
    op.drop_table('dependent')
    op.drop_index(op.f('ix_children_file_output_type_id'), table_name='children_file')
    op.drop_index(op.f('ix_children_file_asset_instance_id'), table_name='children_file')
    op.drop_table('children_file')
    # ### end Alembic commands ###
